server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true              # Auto-discover routes from Eureka
          lower-case-service-id: true # Access services by lowercase name
      routes:
        # Route 1: anything starting with /api/v1/test ? test-service
        - id: test-service
          uri: lb://test-service # "lb://" means load-balanced via Eureka
          predicates:
            - Path=/api/v1/test/**  # Match this URL pattern
          filters:
            # INTERNAL REWRITE: Maps browser '/test' to backend '/api/v1/test'
            # Smart regex prevents forcing  '/' which causes 404s in Spring Boot 3
            - RewritePath=/api/v1/test/(?<segment>.*), /api/v1/test/${segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/auth/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/wallets/**, /api/portfolios/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/smartwealth-realm

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# Better logging to see routing in action
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
